In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
list_of_headers_fortune=['rank', 'company', 'sector', 'industry', 'profitable', 'founder_is_ceo',
       'female_ceo', 'growth_in_jobs', 'change_in_rank', 'gained_in_rank',
       'dropped_in_rank', 'newcomer_to_the_fortune500', 'global500',
       'best_companies', 'number_of_employees', 'marketcap_march31_m',
       'revenues_m', 'revenue_percentchange', 'profits_m',
       'profits_percentchange', 'assets_m', 'country', 'headquarters_state',
       'marketcap_updated_m']

In [8]:
fortune_df = pd.read_excel('./data/excel_fortune_1000_cleaned_2.xlsx', names=list_of_headers_fortune)

In [9]:
fortune_df

,rank,company,sector,industry,profitable,founder_is_ceo,female_ceo,growth_in_jobs,change_in_rank,gained_in_rank,...,number_of_employees,marketcap_march31_m,revenues_m,revenue_percentchange,profits_m,profits_percentchange,assets_m,country,headquarters_state,marketcap_updated_m
0,1,Walmart,Retailing,General Merchandisers,1,0,0,0.0,0,0,...,2100000,397475.0,611289,6.7,11680,-14.6,243197,U.S.,Arkansas,416986.0
1,2,Amazon,Retailing,Internet Services and Retailing,0,0,0,0.0,0,0,...,1541000,1058440.0,513983,9.4,-2722,-108.2,462675,U.S.,Washington,1370373.0
2,3,Exxon Mobil,Energy,Petroleum Refining,1,0,0,0.0,3,1,...,62000,446424.0,413680,44.8,55740,141.9,369067,U.S.,Texas,409878.0
3,4,Apple,Technology,"Computers, Office Equipment",1,0,0,1.0,-1,0,...,164000,2609039.0,394328,7.8,99803,5.4,352755,U.S.,California,3051211.0
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,1,0,0,1.0,0,0,...,400000,440854.0,324162,12.7,20120,16.4,245705,U.S.,Minnesota,450694.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,TTEC Holdings,Technology,Information Technology Services,1,1,0,1.0,-33,0,...,69400,1758.0,2444,7.5,103,-26.8,2154,U.S.,Colorado,1758.0
996,997,ProFrac Holding,Energy,"Oil and Gas Equipment, Services",1,0,0,1.0,Unknown,Unknown,...,3664,2013.0,2426,215.7,92,NaN,2934,U.S.,Texas,2013.0
997,998,Summit Materials,Materials,"Building Materials, Glass",1,0,1,0.0,-61,0,...,4800,3374.0,2413,0.1,272,78.8,4256,U.S.,Colorado,3374.0
998,999,Teladoc Health,Health Care,Health Care: Pharmacy and Other Services,0,0,0,1.0,Unknown,Unknown,...,5208,4212.0,2407,18.4,-13660,NaN,4345,U.S.,New York,4212.0
999,1000,Alliance Resource Partners,Energy,"Mining, Crude-Oil Production",1,0,0,1.0,Unknown,Unknown,...,3371,2566.0,2407,53.3,577,224.0,2662,U.S.,Oklahoma,2566.0

In [10]:
group_df=fortune_df.groupby(['headquarters_state'])
group_df

In [17]:
fortune_df.groupby('headquarters_state')

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000234DCEEBE10>

In [14]:
print(fortune_df.groupby('headquarters_state').head())

     rank             company          sector  \
0       1             Walmart       Retailing
1       2              Amazon       Retailing
2       3         Exxon Mobil          Energy
3       4               Apple      Technology
4       5  UnitedHealth Group     Health Care
..    ...                 ...             ...
893   894             SkyWest  Transportation
895   896          Greenbrier  Transportation
953   954   Hawaiian Holdings  Transportation
965   966       PROG Holdings      Financials
975   976         Black Hills          Energy

                                    industry  profitable  founder_is_ceo  \
0                      General Merchandisers           1               0
1            Internet Services and Retailing           0               0
2                         Petroleum Refining           1               0
3                Computers, Office Equipment           1               0
4    Health Care: Insurance and Managed Care           1               0
..                                       ...         ...             ...
893                                 Airlines           1               0
895                 Transportation Equipment           1               0
953                                 Airlines           0               0
965                   Diversified Financials           1               0
975              Utilities: Gas and Electric           1               0

     female_ceo  growth_in_jobs change_in_rank gained_in_rank  ...  \
0             0             0.0              0              0  ...
1             0             0.0              0              0  ...
2             0             0.0              3              1  ...
3             0             1.0             -1              0  ...
4             0             1.0              0              0  ...
..          ...             ...            ...            ...  ...
893           0             0.0        Unknown        Unknown  ...
895           1             1.0        Unknown        Unknown  ...
953           0             1.0        Unknown        Unknown  ...
965           0             0.0            -67              0  ...
975           0             1.0        Unknown        Unknown  ...

     number_of_employees  marketcap_march31_m  revenues_m  \
0                2100000             397475.0      611289
1                1541000            1058440.0      513983
2                  62000             446424.0      413680
3                 164000            2609039.0      394328
4                 400000             440854.0      324162
..                   ...                  ...         ...
893                12717               1082.0        3005
895                14400               1055.0        2978
953                 7108                471.0        2641
965                 1692               1126.0        2598
975                 2982               4182.0        2552

     revenue_percentchange  profits_m  profits_percentchange  assets_m  \
0                      6.7      11680                  -14.6    243197
1                      9.4      -2722                 -108.2    462675
2                     44.8      55740                  141.9    369067
3                      7.8      99803                    5.4    352755
4                     12.7      20120                   16.4    245705
..                     ...        ...                    ...       ...
893                   10.7         73                  -34.8      7415
895                   70.4         47                   44.4      3852
953                   65.4       -240                    NaN      4140
965                   -3.0         99                  -59.5      1492
975                   30.9        258                    9.1      9618

     country  headquarters_state  marketcap_updated_m
0       U.S.            Arkansas             416986.0
1       U.S.          Washington            1370373.0
2       U.S.               Texas             409878.0
3       U.S.          California            3051211.0
4       U.S.           Minnesota             450694.0
..       ...                 ...                  ...
893     U.S.                Utah               1082.0
895     U.S.              Oregon               1055.0
953     U.S.              Hawaii                471.0
965     U.S.                Utah               1126.0
975     U.S.        South Dakota               4182.0

[185 rows x 24 columns]