In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
list_of_headers_fortune=['rank', 'company', 'sector', 'industry', 'profitable', 'founder_is_ceo',
       'female_ceo', 'growth_in_jobs', 'change_in_rank', 'gained_in_rank',
       'dropped_in_rank', 'newcomer_to_the_fortune500', 'global500',
       'best_companies', 'number_of_employees', 'marketcap_march31_m',
       'revenues_m', 'revenue_percentchange', 'profits_m',
       'profits_percentchange', 'assets_m', 'country', 'state',
       'marketcap_updated_m']

In [4]:
fortune_df = pd.read_excel('./data/excel_fortune_1000_cleaned_2.xlsx', names=list_of_headers_fortune)

In [5]:
fortune_df

,rank,company,sector,industry,profitable,founder_is_ceo,female_ceo,growth_in_jobs,change_in_rank,gained_in_rank,...,number_of_employees,marketcap_march31_m,revenues_m,revenue_percentchange,profits_m,profits_percentchange,assets_m,country,state,marketcap_updated_m
0,1,Walmart,Retailing,General Merchandisers,1,0,0,0.0,0,0,...,2100000,397475.0,611289,6.7,11680,-14.6,243197,U.S.,Arkansas,416986.0
1,2,Amazon,Retailing,Internet Services and Retailing,0,0,0,0.0,0,0,...,1541000,1058440.0,513983,9.4,-2722,-108.2,462675,U.S.,Washington,1370373.0
2,3,Exxon Mobil,Energy,Petroleum Refining,1,0,0,0.0,3,1,...,62000,446424.0,413680,44.8,55740,141.9,369067,U.S.,Texas,409878.0
3,4,Apple,Technology,"Computers, Office Equipment",1,0,0,1.0,-1,0,...,164000,2609039.0,394328,7.8,99803,5.4,352755,U.S.,California,3051211.0
4,5,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,1,0,0,1.0,0,0,...,400000,440854.0,324162,12.7,20120,16.4,245705,U.S.,Minnesota,450694.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,TTEC Holdings,Technology,Information Technology Services,1,1,0,1.0,-33,0,...,69400,1758.0,2444,7.5,103,-26.8,2154,U.S.,Colorado,1758.0
996,997,ProFrac Holding,Energy,"Oil and Gas Equipment, Services",1,0,0,1.0,Unknown,Unknown,...,3664,2013.0,2426,215.7,92,NaN,2934,U.S.,Texas,2013.0
997,998,Summit Materials,Materials,"Building Materials, Glass",1,0,1,0.0,-61,0,...,4800,3374.0,2413,0.1,272,78.8,4256,U.S.,Colorado,3374.0
998,999,Teladoc Health,Health Care,Health Care: Pharmacy and Other Services,0,0,0,1.0,Unknown,Unknown,...,5208,4212.0,2407,18.4,-13660,NaN,4345,U.S.,New York,4212.0
999,1000,Alliance Resource Partners,Energy,"Mining, Crude-Oil Production",1,0,0,1.0,Unknown,Unknown,...,3371,2566.0,2407,53.3,577,224.0,2662,U.S.,Oklahoma,2566.0

In [6]:
fortune_df["sector"].unique()

array(['Retailing', 'Energy', 'Technology', 'Health Care', 'Financials',
       'Motor Vehicles & Parts', 'Food & Drug Stores',
       'Telecommunications', 'Food, Beverages & Tobacco',
       'Transportation', 'Media', 'Household Products', 'Industrials',
       'Wholesalers', 'Aerospace & Defense', 'Chemicals', 'Apparel',
       'Materials', 'Engineering & Construction',
       'Hotels, Restaurants & Leisure', 'Business Services'], dtype=object)

In [7]:
fortune_df["industry"].unique()

array(['General Merchandisers', 'Internet Services and Retailing',
       'Petroleum Refining', 'Computers, Office Equipment',
       'Health Care: Insurance and Managed Care',
       'Health Care: Pharmacy and Other Services',
       'Insurance: Property and Casualty (Stock)',
       'Wholesalers: Health Care', 'Computer Software',
       'Motor Vehicles & Parts', 'Specialty Retailers: Other',
       'Commercial Banks', 'Food and Drug Stores', 'Telecommunications',
       'Diversified Financials', 'Food Production',
       'Mail, Package, and Freight Delivery', 'Pharmaceuticals',
       'Pipelines', 'Insurance: Property and Casualty (Mutual)',
       'Food Consumer Products', 'Entertainment',
       'Mining, Crude-Oil Production', 'Household and Personal Products',
       'Industrial Machinery', 'Insurance: Life, Health (stock)',
       'Wholesalers: Food and Grocery', 'Aerospace & Defense',
       'Semiconductors and Other Electronic Components',
       'Wholesalers: Electronics and Office Equipment',
       'Information Technology Services',
       'Health Care: Medical Facilities',
       'Construction and Farm Machinery', 'Energy',
       'Insurance: Life, Health (Mutual)', 'Chemicals',
       'Network and Other Communications Equipment', 'Airlines',
       'Specialty Retailers: Apparel', 'Apparel',
       'Scientific, Photographic and Control Equipment',
       'Medical Products and Equipment', 'Beverages', 'Metals',
       'Electronics, Electrical Equip.', 'Homebuilders',
       'Automotive Retailing, Services', 'Food Services', 'Tobacco',
       'Real estate', 'Financial Data Services',
       'Utilities: Gas and Electric', 'Railroads',
       'Transportation and Logistics', 'Building Materials, Glass',
       'Securities', 'Wholesalers: Diversified', 'Packaging, Containers',
       'Oil and Gas Equipment, Services', 'Hotels, Casinos, Resorts',
       'Temporary Help', 'Waste Management',
       'Home Equipment, Furnishings', 'Engineering & Construction',
       'Diversified Outsourcing Services', 'Trucking, Truck Leasing',
       'Advertising, marketing', 'Equipment Leasing',
       'Publishing, Printing', 'Forest and Paper Products',
       'Transportation Equipment', 'Toys, Sporting Goods', 'Shipping',
       'Miscellaneous'], dtype=object)

In [8]:
fortune_df["sector"].value_counts()

sector
Financials                       161
Technology                       117
Energy                           115
Health Care                       80
Retailing                         72
Business Services                 52
Industrials                       49
Materials                         48
Transportation                    39
Food, Beverages & Tobacco         33
Wholesalers                       31
Engineering & Construction        31
Chemicals                         28
Hotels, Restaurants & Leisure     28
Media                             28
Household Products                20
Motor Vehicles & Parts            18
Aerospace & Defense               16
Apparel                           16
Food & Drug Stores                 9
Telecommunications                 9
Name: count, dtype: int64

In [9]:
#titanic_df.groupby(["Pclass","Survived"])['Fare'].mean()

In [44]:
grouped_fortune_df = fortune_df.groupby(['state', "sector"])["industry"].describe()

In [45]:
#grouped_fortune_df = fortune_df.groupby('state')["sector"].describe()

In [46]:
#new_df.rename(columns={'headquarters_state':'state'}, inplace=True)

In [47]:
grouped_fortune_df.head(40)

                                         count unique  \
state      sector
Alabama    Financials                        1      1
           Health Care                       1      1
           Materials                         1      1
Arizona    Business Services                 1      1
           Energy                            3      3
           Engineering & Construction        2      1
           Financials                        2      2
           Food & Drug Stores                1      1
           Health Care                       1      1
           Materials                         3      2
           Retailing                         1      1
           Technology                        8      4
           Transportation                    1      1
           Wholesalers                       1      1
Arkansas   Food, Beverages & Tobacco         1      1
           Retailing                         3      2
           Transportation                    2      1
California Aerospace & Defense               1      1
           Apparel                           3      1
           Business Services                 7      4
           Energy                            5      3
           Engineering & Construction        4      2
           Financials                       16      7
           Food & Drug Stores                1      1
           Food, Beverages & Tobacco         1      1
           Health Care                      11      4
           Hotels, Restaurants & Leisure     3      2
           Household Products                3      2
           Media                             7      1
           Retailing                         7      3
           Technology                       52      8
           Wholesalers                       2      2
Colorado   Apparel                           2      1
           Business Services                 1      1
           Energy                            8      3
           Engineering & Construction        3      2
           Health Care                       2      2
           Hotels, Restaurants & Leisure     1      1
           Materials                         2      2
           Media                             1      1

                                                                                     top  \
state      sector
Alabama    Financials                                                   Commercial Banks
           Health Care                                   Health Care: Medical Facilities
           Materials                                           Building Materials, Glass
Arizona    Business Services                                            Waste Management
           Energy                                           Mining, Crude-Oil Production
           Engineering & Construction                                       Homebuilders
           Financials                                                        Real estate
           Food & Drug Stores                                       Food and Drug Stores
           Health Care                                    Medical Products and Equipment
           Materials                                           Building Materials, Glass
           Retailing                                      Automotive Retailing, Services
           Technology                     Semiconductors and Other Electronic Components
           Transportation                                        Trucking, Truck Leasing
           Wholesalers                     Wholesalers: Electronics and Office Equipment
Arkansas   Food, Beverages & Tobacco                                     Food Production
           Retailing                                               General Merchandisers
           Transportation                                        Trucking, Truck Leasing
California Aerospace & Defense                                       Aerospace & Defense
           Apparel                                                               Apparel
           Business Services                                     Financial Data Services
           Energy                                            Utilities: Gas and Electric
           Engineering & Construction                         Engineering & Construction
           Financials                                                   Commercial Banks
           Food & Drug Stores                                       Food and Drug Stores
           Food, Beverages & Tobacco                                           Beverages
           Health Care                                    Medical Products and Equipment
           Hotels, Restaurants & Leisure                                   Food Services
           Household Products                            Household and Personal Products
           Media                                                           Entertainment
           Retailing                                        Specialty Retailers: Apparel
           Technology                                                  Computer Software
           Wholesalers                     Wholesalers: Electronics and Office Equipment
Colorado   Apparel                                                               Apparel
           Business Services                                     Financial Data Services
           Energy                                           Mining, Crude-Oil Production
           Engineering & Construction                                       Homebuilders
           Health Care                                   Health Care: Medical Facilities
           Hotels, Restaurants & Leisure                        Hotels, Casinos, Resorts
           Materials                                               Packaging, Containers
           Media                                                           Entertainment

                                         freq
state      sector
Alabama    Financials                       1
           Health Care                      1
           Materials                        1
Arizona    Business Services                1
           Energy                           1
           Engineering & Construction       2
           Financials                       1
           Food & Drug Stores               1
           Health Care                      1
           Materials                        2
           Retailing                        1
           Technology                       4
           Transportation                   1
           Wholesalers                      1
Arkansas   Food, Beverages & Tobacco        1
           Retailing                        2
           Transportation                   2
California Aerospace & Defense              1
           Apparel                          3
           Business Services                3
           Energy                           3
           Engineering & Construction       3
           Financials                       4
           Food & Drug Stores               1
           Food, Beverages & Tobacco        1
           Health Care                      7
           Hotels, Restaurants & Leisure    2
           Household Products               2
           Media                            7
           Retailing                        3
           Technology                      15
           Wholesalers                      1
Colorado   Apparel                          2
           Business Services                1
           Energy                           6
           Engineering & Construction       2
           Health Care                      1
           Hotels, Restaurants & Leisure    1
           Materials                        1
           Media                            1

In [39]:
list_of_headers_hdi = ["rank", "state", "HDI"]

In [40]:
hdi_df = pd.read_excel('./data/excel_wikipedia.xlsx', names=list_of_headers_hdi)

In [41]:
#hdi_df

In [42]:
merged_df = pd.merge(grouped_fortune_df, hdi_df, on="state")

In [43]:
merged_df.head(30)

,state,count,unique,top,freq,rank,HDI
0,Alabama,3,3,Financials,1,48,0.877
1,Arizona,24,11,Technology,8,37,0.906
2,Arkansas,6,3,Retailing,3,46,0.880
3,California,123,15,Technology,52,15,0.935
4,Colorado,26,13,Energy,8,3,0.952
5,Connecticut,28,12,Financials,6,6,0.950
6,Delaware,7,4,Chemicals,3,29,0.922
7,Florida,39,15,Engineering & Construction,5,26,0.925
8,Georgia,35,14,Financials,6,38,0.905
9,Hawaii,3,2,Transportation,2,7,0.947
10,Idaho,4,4,Food & Drug Stores,1,31,0.916
11,Illinois,59,16,Financials,13,18,0.932
12,Indiana,19,7,Health Care,4,40,0.903
13,Iowa,2,2,Financials,1,28,0.923
14,Kansas,4,4,"Food, Beverages & Tobacco",1,30,0.921
15,Kentucky,6,5,"Hotels, Restaurants & Leisure",2,47,0.879
16,Louisiana,3,3,Telecommunications,1,45,0.881
17,Maine,1,1,Health Care,1,22,0.929
18,Maryland,10,9,Financials,2,10,0.942
19,Massachusetts,31,10,Technology,8,1,0.956
20,Michigan,29,14,Motor Vehicles & Parts,9,32,0.913
21,Minnesota,26,12,Financials,5,5,0.951
22,Missouri,19,9,Financials,4,39,0.904
23,Nebraska,7,5,Financials,2,19,0.931
24,Nevada,10,5,"Hotels, Restaurants & Leisure",6,33,0.910
25,New Hampshire,2,2,Business Services,1,1,0.956
26,New Jersey,24,9,Health Care,7,9,0.943
27,New York,82,18,Financials,31,13,0.937
28,North Carolina,30,13,Materials,5,34,0.908
29,North Dakota,1,1,Energy,1,16,0.934